# Generated by Django 3.1.7 on 2021-04-26 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0003_auto_20210426_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('status_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
