# Generated by Django 3.1.7 on 2021-05-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0005_file_framapath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesection',
            old_name='status_data',
            new_name='status_date',
        ),
    ]
